version: '3.8'
services:
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-server
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./:/usr/share/nginx/html/
volumes:
  html: {}
      